// by protago90

#include "utils.h"


int run_e2v1(int x) {
    int rec = 0;
    int f  = 1;
    int fn = 2;
    while (f <= x) {
    	if (f % 2 == 0) { rec += f; }
        int tmp = f;
        f  = fn;
        fn = fn + tmp;
    }
    return rec;
}

int run_e2v2(int x, int f, int fn) {
    if (f > x) { return 0; }
    int inc = 0;
    int tmp = f;
    if (f % 2 == 0) { inc = f; }
    f  = fn;
    fn = fn + tmp;
    return inc + run_e2v2(x, f, fn);
}


int solve_e2() {
    /**
    * Even Fibonacci numbers
    * Each new term in the Fibonacci sequence is generated by adding the previous two
    * terms. By starting with 1 and 2, the first 10 terms will be:
    * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    * > By considering the terms in the Fibonacci sequence whose values do not exceed
    * four million, find the sum of the even-valued terms. 
    **/
    return run_e2v1(4000000); //, 1, 2); 
}


/** int main() {
    promptify(solve_e2, 2);
    // >> the anwser for the #2 euler problem is >4613732<; computed in 0.0000s ∎
    return 0;
}*/